### ISSUE TITLE
generate gtin 12

### ISSUE THREAD

**Issue by atorralb** [SGLMS/gtin-gs1#1]
Hi there,
I was wondering if from this we could generate a gtin 12 bar code or if you can help add it as a feature?
Since gtin 14 is used for vased products, and gtin 12 is use for retail
Thank you!

**Comment by jaimercz** [comment]
Sure. We'll look into it. We don't work with UPCs, but adding support for them is no problem. Thanks for your comment and star.

**Comment by jaimercz** [comment]
GTIN-12 support added in 1.1.3

**Comment by atorralb** [comment]
Thank you very much amigo.... let me try it
